name: Amazon Module Continuous Integration

on:
  push:
    branches: [ master ]
    paths: ['driver/amazon/**.go']
  pull_request:
    branches: [ master ]
    paths: ['driver/amazon/**.go']

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Run Unit Testing
        run: cd ./driver/amazon && go test ./...
      - name: Start Infrastructure
        run: cd ./driver/amazon/testinfra/sh-amazon-ci && docker-compose up -d
      - name: Run Integration Testing
        run: cd ./driver/amazon && go test ./... -tags=integration
